---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

GDBackend:
  default_quality: 90

Image:
  cms_thumbnail_width:  100
  cms_thumbnail_height: 80
  force_resample: true

LeftAndMain:
  cms_highlight_colour : '#282828'
  cms_success_color : '#333333'
  cms_error_color : '#e94f35'
  cms_style_tinymce: false
  extra_requirements_css:
    - mysite/styles/custom.css